const documents = {
  CMW: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  CMW_UK: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  WILDVIGNERON: {
    topbar: 'wv_topbar',
    homeBoxes: 'wv_home-boxes',
    productors: 'wv_productors',
    shipping: 'wv_shipping',
    aboutUs: 'wv_about_us',
    shippingPage: 'wv_shipping-page',
    paymentsPage: 'wv_payments',
    conditionsPage: 'wv_conditions',
    contactPage: 'wv_contact_us',
    privacyPage: 'wv_privacy-policy',
    cookiePage: 'wv_cookie-policy',
  },
}

export default documents
