const documents = {
  CMW: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  B2B: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  CMW_UK: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  CMW_FR: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
  CMW_DE: {
    topbar: 'topbar',
    homeBoxes: 'home-boxes',
    productors: 'productors',
    shipping: 'shipping',
    aboutUs: 'about_us',
    shippingPage: 'shipping-page',
    paymentsPage: 'payments',
    conditionsPage: 'conditions',
    contactPage: 'contact_us',
    privacyPage: 'privacy-policy',
    cookiePage: 'cookie-policy',
  },
}

export default documents
